board_width = 120
board_height = 25
paddle_init_width = 3
paddle_row_restriction = board_height - 1
prob_powerup = 0.75
powerup_status = {'MISSED': -1, 'SPAWNED': 0, 'ACTIVE': 1, 'DISABLED': 2}
ball_speed_interval = 0.06
time_attack_limit = [-1, 5, 10, 100, 10]
shooting_interval = 3
shooting_duration = 10
bomb_interval = 15
bomb_speed = 0.5
